title: Spans' Blog
email: me@spans.fi
description: >- # this means to ignore newlines until "baseurl:"
baseurl: ""
url: "https://blog.spans.fi"
twitter_username:
github_username: spanfile

remote_theme: jekyll/minima
minima:
  skin: dark

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-remote-theme
