title: Spans' Blog
email: me@spans.fi
description: >- # this means to ignore newlines until "baseurl:"
baseurl: ""
url: "https://blog.spans.fi"
twitter_username: 
github_username:  spanfile

theme: minima
plugins:
  - jekyll-feed
